FROM node:20-bookworm
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npx prisma generate
COPY tsconfig.json nest-cli.json ./
COPY .prettierignore .prettierrc.json eslint.config.mjs ./
COPY src ./src
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
